### ISSUE TITLE
Cant see flag images in web release mode hosted of FB hosting.

### ISSUE THREAD

**Issue by kaumudpa** [Daniel-Ioannou/flutter_country_picker#16]
<img width="353" alt="Screenshot 2021-02-23 at 5 23 17 PM" src="https://user-images.githubusercontent.com/13520180/108840256-19cce980-75fc-11eb-8c6c-919ca300bdd0.png">

Works fine in debug mode but not in release mode.

**Comment by Daniel-Ioannou** [comment]
@kaumudpa Thanks for the feedback. 
I will fix this issue in the next version. For now run/build with `--web-renderer=html`

**Comment by kaumudpa** [comment]
My app needs skia to render some content.

**Comment by Daniel-Ioannou** [comment]
@kaumudpa Package use unicode(emojis) for flags, If you have any idea why is not displayed in the web platform  let me know.

**Comment by mz185** [comment]
Any update?

**Comment by Daniel-Ioannou** [comment]
Released in [v2.0.21](https://pub.dev/packages/country_picker/versions/2.0.21).
