### ISSUE TITLE
country localized name is wong

### ISSUE THREAD

**Issue by nag4r** [Daniel-Ioannou/flutter_country_picker#169]
country named east timor and the arabic name is not correct جمهورية الكونغو الديمقراطية ,the correct arabic name is تيمور الشرقية

**Comment by nag4r** [comment]
please update this small issue

**Comment by nag4r** [comment]
thanks

**Comment by Daniel-Ioannou** [comment]
@nag4r Thank you for your contribution, Released in [v2.0.27](https://pub.dev/packages/country_picker/versions/2.0.27).
