### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by marchellodev** [Daniel-Ioannou/flutter_country_picker#17]
Right now it's impossible to define custom colors for the pop-up

**Comment by Daniel-Ioannou** [comment]
At v2.0.1 was added `countryListTheme` parameter for customizing the country pop-up.
   ```Dart
   showCountryPicker(
     context: context,
     countryListTheme: CountryListThemeData(
       flagSize: 25,
       backgroundColor: Colors.white,
       textStyle: TextStyle(fontSize: 16, color: Colors.blueGrey),
     ),
     onSelect: (Country country) => print('Select country: ${country.displayName}'),
   );
   ```
For more info check the documentation [documentation](https://pub.dev/documentation/country_picker/latest/country_picker/CountryListThemeData-class.html).
