### ISSUE TITLE
country localization for maximum Asian countries 

### ISSUE THREAD

**Issue by sachin-dahal** [Daniel-Ioannou/flutter_country_picker#34]
Hello maintainers!
The country name translation and localizations are done very well in the package. But I couldn't find the country name localizations for most of the Asian countries [🇳🇵, 🇮🇳, 🇧🇹, 🇵🇰, 🇧🇩 ] including mine.
It would be much better to configure the localization feature for Asian countries too.
:)

**Comment by sachin-dahal** [comment]
issue has been closed in the PR #35

**Comment by Daniel-Ioannou** [comment]
v2.0.6 released.
