### ISSUE TITLE
Search initially activated (focus) 

### ISSUE THREAD

**Issue by FilipKvestak** [Daniel-Ioannou/flutter_country_picker#39]
Is it possible to initially have focus on search bar, with virtual keyboard up?

**Comment by Daniel-Ioannou** [comment]
@FilipKvestak You mean when the bottom sheet open to have focus on search bar?

**Comment by FilipKvestak** [comment]
yes, when we open bottom sheet (country picker) to have it automatically focused on search

**Comment by Daniel-Ioannou** [comment]
Released in [v2.0.8](https://github.com/Daniel-Ioannou/flutter_country_picker/releases/tag/v2.0.8).
