### ISSUE TITLE
Set the height of bottom sheet or adapt it to content

### ISSUE THREAD

**Issue by davemg3** [Daniel-Ioannou/flutter_country_picker#49]
Hi,
Great package but could you tell me if you plan to improve display by making the bottom sheet with adaptive height to content or at least being able to set the height to a specific height?

**Comment by janar265** [comment]
Hey, created a PR for that 
https://github.com/Daniel-Ioannou/flutter_country_picker/pull/73

**Comment by Daniel-Ioannou** [comment]
Released in [v2.0.13](https://pub.dev/packages/country_picker/versions/2.0.13)
