### ISSUE TITLE
Get flag images on selected

### ISSUE THREAD

**Issue by jvanleersum** [Daniel-Ioannou/flutter_country_picker#75]
Hi! Thanks for your great package! I was wondering if it was possible to extract the flag image once a country is selected? Thanks!

**Comment by janar265** [comment]
Hi, I managed to that by using the same functionality as the library uses so to render it you would need to display it in Text widget for example: 

```
Text(
      Utils.countryCodeToEmoji(selectedCountry.countryCode),
      style: const TextStyle(
        fontSize: 20,
      ),
);
```

The countryCodeToEmoji is in lib/src/utils.dart
So when selecting country you get the Country object and from there you can get countryCode and with that you can easily display the flag emoji.

**Comment by Daniel-Ioannou** [comment]
Hi @jvanleersum please check discussion #68.
