### ISSUE TITLE
Initial Country 

### ISSUE THREAD

**Issue by AamilLiveKeeping** [Daniel-Ioannou/flutter_country_picker#89]
How can i set Initial Country in textfield ? For eg. I have to fetch Country from API then i must have to pass some CountryCode arguments!!!!

**Comment by Daniel-Ioannou** [comment]
@AamilLiveKeeping, Not sure if I understand what you mean by "Initial Country in textfield". Can you please elaborate more or provide a code example?

**Comment by AamilLiveKeeping** [comment]
> 

Like this

`  // Initial selection and favorite can be one of code ('IT') OR dial_code('+39')
                                  initialSelection: 'IN',`
                                  
 What is happening now if i entered country code instead of ISO 24 (country name) it is not throwing error we should provide both country code as well as ISO 24 name 
 
 For more info reach out this plug in [country_code_picker](https://pub.dev/packages/country_code_picker)

**Comment by Daniel-Ioannou** [comment]
[country_picker](https://pub.dev/packages/country_picker) and [country_code_picker](https://pub.dev/packages/country_code_picker) is not the same package. 
This package([country_picker](https://pub.dev/packages/country_picker)) provide a bottom sheet dialog with a list of countries. The package does not hold the state of the selected country so there is no need for a initial country.


In the example below a local variable hold the selected country not the package.
You can initialize this local variable from your API using ` CountryParser.tryParse("")`.
 ```Dart
import 'package:country_picker/country_picker.dart';

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  Country? _country;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Demo for country picker')),
      body: Center(
        child: InkWell(
          onTap: () {
            showCountryPicker(
              context: context,
              onSelect: (Country country) {
                setState(() => _country = country);
              },
            );
          },
          child: Text(_country?.name ?? "Select a country"),
        ),
      ),
    );
  }
}
```


For more information please check the [documentation](https://pub.dev/documentation/country_picker/latest/).
